---
- name: build new inventory
  hosts: "{{ prefix }}*"
  become: yes
  gather_facts: yes

  tasks:
  - name: fix partition
  # parted module doesnt do this
    command: "growpart /dev/vda 1"
    ignore_errors: true

  - name: fix filesystem
  # TO-DO use filesystem module maybe
    command: "resize2fs /dev/vda1"

  - name: show the filesystem actual size
  # TO-DO use facts to assert a minimum size
    command: "df -HT"
    register: my_out

  - debug: var=my_out

  - name: update all packages
    package:
      name: "*"
      state: latest

  - name: reboot everything clean
    reboot:
