---
- name: simple fact gather and output from Pure FlashBlade module
  gather_facts: no
  become: no
  hosts: localhost

  tasks:
    - name: gather Pure FB facts
      local_action:
        module: purefb_facts
        gather_subset: all
#        fb_url: "{{ fb_url }}"
#        api_token: "{{ fb_token }}"

    - name: output
      debug: var=ansible_purefb_facts
