---
# tasks file for add_fa_host
- name: set FA host name
  set_fact:
    fa_hostname: "{{ ansible_facts.hostname | regex_replace('\\.','-') }}"

- name: create the host
  local_action:
    module: purestorage.flasharray.purefa_host
    name: "{{ fa_hostname }}"
    state: "{{ my_state | default('present') }}"
    iqn: "{{ iscsi_iqn }}"
    protocol: iscsi

- name: add to hostgroup
  throttle: 1 # to prevent race on create hg
  local_action:
    module: purestorage.flasharray.purefa_hg
    hostgroup: "{{ hostgroup_name }}"
    state: "{{ my_state | default('present') }}"
    host:
      - "{{ ansible_facts.hostname }}"
  when: ( hostgroup_name is defined ) and ( add_hostgroup|bool )
