apiVersion: v1
baseDomain: dfwlab.purestorage.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    openstack:
      rootVolume:
        size: 40
        type: fa-x50
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    openstack:
      rootVolume:
        size: 40
        type: fa-x50
  replicas: 3
metadata:
  creationTimestamp: null
  name: ospocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    apiVIP: 10.0.0.5
    cloud: shiftstack
    computeFlavor: openshift
    externalDNS: ["10.228.112.8","10.228.112.7"]
    externalNetwork: public
    ingressVIP: 10.0.0.7
    lbFloatingIP: 10.228.113.109
    octaviaSupport: "0"
    region: ""
    trunkSupport: "1"
publish: External
pullSecret: '{pullsecret}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiRSZHAAtSKBZNvaqt/P297bU+pv9wqLZ7Y+yAO3p/+F9XTNtH7NDWpMkMD872TEIa5WOQSZN2CYdnh0ZUZf7ODMehUas186V/X2aPAaVm8vHB+u2C36W6X4y19k9XMhPbbbZh3SikdHeXJT3pjuBIiytzbX2Khd3+wyTwDEZt+np+NIFzd5uw0nJHW3puhJk3HOc5qoI+M85+tcSvM55tEYuz/OOmu3Mz4qbQAjq8mTj+hXiAuBm0Eq9Z1mScz5oU5l8zCvtwx/Pqro+/ATSZsT/71RhzxBkIfeMFtZYeU8ZSSHGgBBUOeCMklAX/43PYwktOS5nciLZNV7WsDpLP
